server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-sept
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console